#Add debug for PMUFW
#XSCTH_BUILD_DEBUG = "1"

ULTRA96_VERSION = "2"
YAML_COMPILER_FLAGS_append_ultra96-zynqmp = "-DENABLE_MOD_ULTRA96 -DENABLE_SCHEDULER -DENABLE_EM -DENABLE_PM -DENABLE_WDT -DENABLE_RECOVERY -DENABLE_ESCALATION -DENABLE_NODE_IDLING -DREMOVE_GPIO_FROM_NODE_RESET_INFO -DCHECK_HEALTHY_BOOT -DIDLE_PERIPHERALS"
YAML_COMPILER_FLAGS_append_ultra96-zynqmp = "${@bb.utils.contains('ULTRA96_VERSION', '2', ' -DULTRA96_VERSION=2', ' -DULTRA96_VERSION=1', d)}"

